### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by hhirsch** [mako-framework/app#5]
I liked this a lot until I noticed that there is no example application or tutorial that shows how everything works together.

**Comment by thegoodlifedesign** [comment]
is this framework like a wrapper around laravel?

**Comment by letr0n** [comment]
no

**Comment by hhirsch** [comment]
laravel ftw

**Comment by thegoodlifedesign** [comment]
@letr0n it has very similar api and implementations I guess you could say its inspired by Laravel?
