### ISSUE TITLE
v4.4.1 Composer requiring wrong framework version

### ISSUE THREAD

**Issue by telephone** [mako-framework/app#7]
__Version: 4.4.1 and Version 4.4.x-dev__

Composer is using incorrect version for `mako/framework`:

```
mako/framework: 4.5.*
```

Instead of:

```
mako/framework: 4.4.*
```

Verified on [Packagist](https://packagist.org/packages/mako/app)

**Comment by freost** [comment]
Thanks :) Have re-tagged 4.4.1 with the correct requirements.
